[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GeoPro"
authors = [{name = "Andrei Harbachov", email = "andrei_harbachov@sfu.ca"}]
dynamic = ["version", "description"]
